queue_rules:
  - name: lowprio
    conditions:
      - schedule=Mon-Fri 09:30-16:00[Europe/Paris]

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "#commits=1"
    actions:
      queue:
        name: lowprio
        method: rebase
