queue_rules:
  - name: default
    conditions:
      - schedule=Mon-Fri 09:30-16:00[Europe/Paris]

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "#commits=1"
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
        update_method: rebase
