version: 1
update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          update_type: all
    commit_message:
      prefix: build
      include_scope: true
  - package_manager: docker
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          update_type: all
    commit_message:
      prefix: build
      include_scope: true
  - package_manager: github_actions
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          update_type: all
    commit_message:
      prefix: build
      include_scope: true
