name: CI
on:
  push:
    branches-ignore:
      - master
      - dependabot/**
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Markdown files
        uses: actionshub/markdownlint@v1.1.1

      - name: Lint YAML files
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |-
          docker build -f Dockerfile .
