name: Release

on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - Dockerfile
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Lint Markdown files
        uses: actionshub/markdownlint@2.0.2

      - name: Lint YAML files
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |-
          DOCKERHUB_USERNAME=$(echo $GITHUB_REPOSITORY | awk -F"/" '{print $1}')
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build and push image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |-
          set -ex

          IMAGE_ID=$GITHUB_REPOSITORY
          IMAGE_TAG=${{ steps.semantic.outputs.new_release_version }}
          VERSION=${{ steps.semantic.outputs.new_release_version }}

          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_TAG=$IMAGE_TAG
          echo VERSION=$VERSION

          docker build \
            --tag $IMAGE_ID:latest \
            --tag $IMAGE_ID:$IMAGE_TAG \
            --build-arg VERSION=$VERSION \
            -f Dockerfile \
            .

          docker push --all-tags $IMAGE_ID
