name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |-
          set -ex

          IMAGE_ID=$GITHUB_REPOSITORY
          VERSION=$GITHUB_SHA

          # Strip "v" prefix from tag name
          if [[ "$GITHUB_REF" == "refs/tags/v"* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker build \
            --tag $IMAGE_ID:latest \
            --tag $IMAGE_ID:$VERSION \
            --build-arg VERSION=$VERSION \
            -f Dockerfile \
            .

          docker push --all-tags $IMAGE_ID
